GlobalConfigs:
  default_output_dir: "./20260130-PiIDStudy-pipiLoose"
  region_of_interest: &RegionName "pipiLoose"
  load_regions:
    - *RegionName
    - "raw"
  luminosity: &Luminosity 46.3 # pb^-1
  signal_categories:
    - 11

DataLoaders:
  data94:
    name: "data94"
    tree_name: "t"
    is_data: true
    is_signal: false
    input_files:
      - "/eos/home-y/yulei/Ztautau/ntuple/collision_datanew/v94c/91.25/nanoaod_*.al_ttree.root"
  
  Ztautau:
    name: "Ztautau"
    tree_name: "t"
    is_data: false
    is_signal: false
    norm_factor: 1458.9 # pb
    input_files:
      - "/eos/user/y/yulei/Ztautau/ntuple/simu_20251130/v94c/Z_tautaunew/simana_*_ttree.root"
      
  Zll:
    name: "Zll"
    tree_name: "t"
    is_data: false
    is_signal: false
    norm_factor:  2844.4 # pb
    input_files:
      - "/eos/user/y/yulei/Ztautau/ntuple/simu_20251130/v94c/Z_llnew/simana_*_ttree.root"

  Zqq:
    name: "Zqq"
    tree_name: "t"
    is_data: false
    is_signal: false
    norm_factor: 30511.2 # pb
    input_files:
      - "/eos/user/y/yulei/Ztautau/ntuple/simu_20251130/v94c/Z_qqnew/simana_*_ttree.root"

Processors:
  # PlotProcessor: 
  # TemporaryProcessor: 
  ControlPlotProcessor:
    output_dir_name: "control_plots"
    regions:
      # - "pipi"
      # - "leplep"
      - "pipiLoose"
  # NeutrinoReconstructionProcessor:
  IDAnaProcessor:
    output_dir_name: "ID_analysis"
    targeted_recon_pdgId: 
      - 41
      # - 6
      # - 2
    regions:
      # - "pipi"
      # - "leplep"
      - "pipiLoose"
      # - "raw"
