default_output_dir: "./output/"

DataLoaders:
  data94:
    name: "data94"
    tree_name: "t"
    region_of_interest: "pipi"
    is_data: true
    input_files:
      - "/eos/user/c/cmo/project/ZtautauLep/simulation/run/collision_data/v94c/91.25/nanoaod_*.al_ttree.root"
  
  Ztautau_pipm:
    name: "Ztautau_pipm"
    tree_name: "t"
    region_of_interest: "pipi"
    is_data: false
    input_files:
      - "/eos/home-c/cmo/project/ZtautauLep/simulation/run/251108_Ztautau_pipm/simana_job_*_ttree_pipi.root"

Processors:
  PlotProcessor: None
  TemporaryProcessor: None
