GlobalConfigs:
  default_output_dir: "./20260427-dataset/"
  max_input_slice_size_gb: 50
  num_workers: 8
  luminosity: &Luminosity 46.3 # pb^-1

DataLoaders:
  data94:
    name: "data94"
    tree_name: "t"
    is_data: true
    is_signal: false
    input_files:
      - "/eos/home-y/yulei/Ztautau/ntuple/collision_data_v3/v94c/91.25/nanoaod_*.al_ttree.root"
  
  Ztautau:
    name: "Ztautau"
    tree_name: "t"
    is_data: false
    is_signal: false
    norm_factor: 1458.9 # pb
    input_files:
      - "/eos/user/y/yulei/Ztautau/ntuple/simu_20251130/v94c/Z_tautau_v3/simana_*_ttree.root"
      
  Zll:
    name: "Zll"
    tree_name: "t"
    is_data: false
    is_signal: false
    norm_factor:  2844.4 # pb
    input_files:
      - "/eos/user/y/yulei/Ztautau/ntuple/simu_20251130/v94c/Z_ll_v3/simana_*_ttree.root"

  Zqq:
    name: "Zqq"
    tree_name: "t"
    is_data: false
    is_signal: false
    norm_factor: 30511.2 # pb
    input_files:
      - "/eos/user/y/yulei/Ztautau/ntuple/simu_20251130/v94c/Z_qq_v3/simana_*_ttree.root"
