Samples:
  data94:
    name: "data94"
    is_data: true
    is_signal: false
    lumi: 46.3 # pb^-1
    input_files:
      - "/global/cfs/cdirs/m5019/Ztautau_LEP/preselected_parquets/20260212-pion-channel/data94/filtered___tautau.parquet"

  Ztautau:
    name: "Ztautau"
    is_data: false
    is_signal: true
    norm_factor: 1458.9 # pb
    input_files:
      - "/global/cfs/cdirs/m5019/Ztautau_LEP/preselected_parquets/20260212-pion-channel/Ztautau/filtered___tautau.parquet"

  Zll:
    name: "Zll"
    is_data: false
    is_signal: false
    norm_factor:  2844.4 # pb
    input_files:
      - "/global/cfs/cdirs/m5019/Ztautau_LEP/preselected_parquets/20260212-pion-channel/Zll/filtered___tautau.parquet"

  Zqq:
    name: "Zqq"
    is_data: false
    is_signal: false
    norm_factor: 30511.2 # pb
    input_files:
      - "/global/cfs/cdirs/m5019/Ztautau_LEP/preselected_parquets/20260212-pion-channel/Zqq/filtered___tautau.parquet"

Inputs:
  Part:
    Momentum:
      dim: 4
      index: [0, 1, 2, 3]
      input: [energy, pt, eta, phi]
    ObjectTag:
      dim: 2
      index: [4, 5]
      input:
        - Part_pdgId
        - hpc:
            dim: 2
            input:
              - Part_hpcShowerEnergy
              - Part_hpcShowerTheta
              - Part_hpcShowerPhi
              - Part_hpcNumLayers
              - Part_hpcNumAssociatedShowers
              - Part_hpcTotalShowerEnergy
        - hac:
            dim: 2
            input:
              - Part_hacShowerEnergy
              - Part_hacShowerTheta
              - Part_hacShowerPhi
              - Part_hacNumTowers
              - Part_hacNumAssociatedShowers
              - Part_hacTotalShowerEnergy
        - stic:
            dim: 2
            input:
              - Part_sticShowerEnergy
              - Part_sticShowerTheta
              - Part_sticShowerPhi
              - Part_sticNumTowers
              - Part_sticChargedTag
    Charge:
      dim: 1
      index: [6]
      input:
        - Part_charge
  Global:
    Fields:
      - Event_totalChargedEnergy
      - Event_totalEMEnergy
      - Event_totalHadronicEnergy
      - thrust_Mag
      - charged_E
      - missing_px
      - missing_py
      - missing_pt
      - isolation_angle
      - thrust_x
      - thrust_y
      - thrust_z

Subcategories:
  Ztautau:
    Ztautau_pipi: [11]
    Ztautau_pirho: [12, 21]
    Ztautau_pie: [13, 31]
    Ztautau_pimu: [14, 41]
    Ztautau_rhoe: [23, 32]
    Ztautau_rhomu: [42, 24]
    Ztautau_rhorho: [22]
    Ztautau_ee: [33]
    Ztautau_mumu: [44]
    Ztautau_emu: [34, 43]
#    Ztautau_piother: [15, 51]

Normalization:
  Sequential:
    default: none
    Part_energy: log_normalize
    Part_pt: log_normalize
    Part_eta: normalize
    Part_phi: normalize_uniform
    Part_hpcShowerEnergy: normalize
    Part_hpcShowerTheta: normalize
    Part_hpcShowerPhi: normalize
    Part_hpcNumLayers: normalize
    Part_hpcNumAssociatedShowers: normalize
    Part_hpcTotalShowerEnergy: normalize
    Part_hacShowerEnergy: normalize
    Part_hacShowerTheta: normalize
    Part_hacShowerPhi: normalize
    Part_hacNumTowers: normalize
    Part_hacNumAssociatedShowers: normalize
    Part_hacTotalShowerEnergy: normalize
    Part_sticShowerEnergy: normalize
    Part_sticShowerTheta: normalize
    Part_sticShowerPhi: normalize
    Part_sticNumTowers: normalize
  Global:
    default: none
    Event_totalChargedEnergy: log_normalize
    Event_totalEMEnergy: log_normalize
    Event_totalHadronicEnergy: log_normalize
    thrust_Mag: normalize
    charged_E: log_normalize
    missing_px: normalize
    missing_py: normalize
    missing_pt: normalize
    isolation_angle: normalize
    thrust_x: normalize
    thrust_y: normalize
    thrust_z: normalize
  Invisible:
    default: none
    mass: normalize
    pt: normalize
    eta: normalize
    phi: normalize_uniform
