Samples:
  data94:
    name: "data94"
    is_data: true
    is_signal: false
    lumi: 46.3 # pb^-1
    input_files:
      - "/global/cfs/cdirs/m5019/Ztautau_LEP/preselected_parquets/20260212-pion-channel/data94/filtered___tautau.parquet"

  Ztautau:
    name: "Ztautau"
    is_data: false
    is_signal: false
    norm_factor: 1458.9 # pb
    input_files:
      - "/global/cfs/cdirs/m5019/Ztautau_LEP/preselected_parquets/20260212-pion-channel/Ztautau/filtered___tautau.parquet"

  Zll:
    name: "Zll"
    is_data: false
    is_signal: false
    norm_factor:  2844.4 # pb
    input_files:
      - "/global/cfs/cdirs/m5019/Ztautau_LEP/preselected_parquets/20260212-pion-channel/Zll/filtered___tautau.parquet"

  Zqq:
    name: "Zqq"
    is_data: false
    is_signal: false
    norm_factor: 30511.2 # pb
    input_files:
      - "/global/cfs/cdirs/m5019/Ztautau_LEP/preselected_parquets/20260212-pion-channel/Zqq/filtered___tautau.parquet"

Inputs:
  Part:
    Momentum: [energy, pt, eta, phi]
    Auxiliary:
      - Part_charge
      - Part_pdgId
      - Part_vtxIdx
      - Part_hpcShowerEnergy
      - Part_hpcShowerTheta
      - Part_hpcShowerPhi
      - Part_hpcParticleCode
      - Part_hpcNumLayers
      - Part_hpcLayerHitPattern
      - Part_hpcNumAssociatedShowers
      - Part_hpcTotalShowerEnergy
      - Part_hacShowerEnergy
      - Part_hacShowerTheta
      - Part_hacShowerPhi
      - Part_hacParticleCode
      - Part_hacNumTowers
      - Part_hacTowerHitPattern
      - Part_hacNumAssociatedShowers
      - Part_hacTotalShowerEnergy
      - Part_sticShowerEnergy
      - Part_sticShowerTheta
      - Part_sticShowerPhi
      - Part_sticNumTowers
      - Part_sticChargedTag
      - Part_sticSiliconVertexPos
      - Part_hemisphere
  Global:
    Fields:
      - Event_totalChargedEnergy
      - Event_totalEMEnergy
      - Event_totalHadronicEnergy
      - thrust_Mag
      - charged_E
      - missing_px
      - missing_py
      - missing_pt
      - isolation_angle
      - thrust_x
      - thrust_y
      - thrust_z

Subcategories:
  Ztautau:
    Ztautau_pipi: [11]
    Ztautau_pirho: [12, 21]
    Ztautau_pilep: [13, 31, 14, 41]
    Ztautau_rhorho: [22]
    Ztautau_leplep: [33, 34, 43, 44]
    Ztautau_piother: [15, 51]

EveNet:
  Classification:
    Name: process

  Processes:
    Ztautau_pipi:
      tau_minus:
        - tau_minus_vis
      tau_plus:
        - tau_plus_vis
    Ztautau_pirho:
      tau_minus:
        - tau_minus_vis
      tau_plus:
        - tau_plus_vis
    Ztautau_pilep:
      tau_minus:
        - tau_minus_vis
      tau_plus:
        - tau_plus_vis
    Ztautau_rhorho:
      tau_minus:
        - tau_minus_vis
      tau_plus:
        - tau_plus_vis
    Ztautau_leplep:
      tau_minus:
        - tau_minus_vis
      tau_plus:
        - tau_plus_vis
    Ztautau_piother:
      tau_minus:
        - tau_minus_vis
      tau_plus:
        - tau_plus_vis
    Ztautau_others:
      tau_minus:
        - tau_minus_vis
      tau_plus:
        - tau_plus_vis
    Zll:
      z_boson:
        - lep_minus
        - lep_plus
    Zqq:
      z_boson:
        - jet_1
        - jet_2

  Generations:
    Conditions:
      - Event_totalChargedEnergy
      - Event_totalEMEnergy
      - Event_totalHadronicEnergy
      - thrust_Mag
      - charged_E
      - missing_px
      - missing_py
      - missing_pt
      - isolation_angle
      - thrust_x
      - thrust_y
      - thrust_z
    GlobalTargets: []
    Events:
      - Part_energy
      - Part_pt
      - Part_eta
      - Part_phi

Normalization:
  Sequential:
    default: none
    Part_energy: log_normalize
    Part_pt: log_normalize
    Part_eta: normalize
    Part_phi: normalize_uniform
  Global:
    default: none
    Event_totalChargedEnergy: log_normalize
    Event_totalEMEnergy: log_normalize
    Event_totalHadronicEnergy: log_normalize
    thrust_Mag: normalize
    charged_E: log_normalize
    missing_px: normalize
    missing_py: normalize
    missing_pt: log_normalize
    isolation_angle: normalize
    thrust_x: normalize
    thrust_y: normalize
    thrust_z: normalize
  Invisible:
    default: none
    energy: log_normalize
    pt: log_normalize
    eta: normalize
    phi: normalize_uniform
