Classification:
  Name: process

Processes:
  Ztautau_pipi:
    tau_minus:
      - tau_minus_vis
    tau_plus:
      - tau_plus_vis
  Ztautau_pirho:
    tau_minus:
      - tau_minus_vis
    tau_plus:
      - tau_plus_vis
  Ztautau_pilep:
    tau_minus:
      - tau_minus_vis
    tau_plus:
      - tau_plus_vis
  Ztautau_rhorho:
    tau_minus:
      - tau_minus_vis
    tau_plus:
      - tau_plus_vis
  Ztautau_leplep:
    tau_minus:
      - tau_minus_vis
    tau_plus:
      - tau_plus_vis
  Ztautau_piother:
    tau_minus:
      - tau_minus_vis
    tau_plus:
      - tau_plus_vis
  Ztautau_others:
    tau_minus:
      - tau_minus_vis
    tau_plus:
      - tau_plus_vis
  Zll:
    z_boson:
      - lep_minus
      - lep_plus
  Zqq:
    z_boson:
      - jet_1
      - jet_2

Generations:
  Conditions:
    - Event_totalChargedEnergy
    - Event_totalEMEnergy
    - Event_totalHadronicEnergy
    - thrust_Mag
    - charged_E
    - missing_px
    - missing_py
    - missing_pt
    - isolation_angle
    - thrust_x
    - thrust_y
    - thrust_z
  GlobalTargets: []
  Events:
    - Part_energy
    - Part_pt
    - Part_eta
    - Part_phi
