Classification:
  Name: process

Processes:
  Ztautau_pipi:
    "tau-":
      - "vis-"
    "tau+":
      - "vis+"
  Ztautau_pirho:
    "tau-":
      - "vis-"
    "tau+":
      - "vis+"
  Ztautau_pilep:
    "tau-":
      - "vis-"
    "tau+":
      - "vis+"
  Ztautau_rhorho:
    "tau-":
      - "vis-"
    "tau+":
      - "vis+"
  Ztautau_leplep:
    "tau-":
      - "vis-"
    "tau+":
      - "vis+"
  Ztautau_piother:
    "tau-":
      - "vis-"
    "tau+":
      - "vis+"
  Ztautau_others:
    "tau-":
      - "vis-"
    "tau+":
      - "vis+"
  Zll:
    Z:
      - l1
      - l2
  Zqq:
    Z:
      - q1
      - q2

Generations:
  Conditions:
    - Event_totalChargedEnergy
    - Event_totalEMEnergy
    - Event_totalHadronicEnergy
    - thrust_Mag
    - charged_E
    - missing_px
    - missing_py
    - missing_pt
    - isolation_angle
    - thrust_x
    - thrust_y
    - thrust_z
  GlobalTargets: []
  Events:
    - Part_energy
    - Part_pt
    - Part_eta
    - Part_phi
