default: ../EveNet-Full/share/network/network-20M.yaml

Body:
  GroupedSequentialEmbedding:
    hidden_dim_scale: 2.0
    dropout: 0.0

  PET:
    feature_drop: 0.0

TruthGeneration:
  feature_drop: 0.0
