default: ../EveNet-Full/share/options/options.yaml

Training:
  total_epochs: 100
  epochs: 100
  model_checkpoint_save_path: <model_checkpoint_save_path>
  model_checkpoint_load_path: null
  pretrain_model_load_path: null
  freeze_modules: []

  diffusion_every_n_epochs: 4
  diffusion_every_n_steps: 1
  eval_metrics_every_n_epochs: 1
  apply_event_weight: false

  Components:
    GroupedSequentialEmbedding:
      learning_rate: 0.001
      optimizer_group: "body"
      optimizer_type: "lion"
      warm_up: true
      weight_decay: 0.01
      decoupled_weight_decay: true

    InvisibleInputProjector:
      learning_rate: 0.001
      optimizer_group: "projector"
      optimizer_type: "lion"
      warm_up: true
      weight_decay: 0.01
      decoupled_weight_decay: true


    Classification:
      include: true

    Regression:
      include: false

    Assignment:
      include: false

    Segmentation:
      include: false
      use_full_mask: true

    GlobalGeneration:
      include: false
      diffusion_steps: 2

    ReconGeneration:
      include: false
      diffusion_steps: 2

    TruthGeneration:
      include: true
      diffusion_steps: 2

  EarlyStopping:
    patience: 100
    min_delta: 0.0
    monitor: "val/loss"
    mode: "min"
    verbose: true

  FAMO:
    turn_on: false
    detailed_loss: false

  EMA:
    enable: true
    decay: 0.999
    start_epoch: 0
    update_every_n_steps: 1
    replace_model_after_load: true
    replace_model_at_end: false

  ProgressiveTraining:
    stages:
      - name: "full_training"
        epoch_ratio: 1.0
        transition_ratio: 0.0
        loss_weights:
          generation-truth: [ 1.5, 1.5 ]
          classification: [ 1.0, 1.0 ]

Dataset:
  dataset_limit: 1.0
  normalization_file: <normalization_file>
  val_split: [0.95, 1.0]
