platform:
  data_parquet_dir: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/event-input
  number_of_workers: 1
  resources_per_worker: {
    "CPU": 1,
    "GPU": 1,
  }
  batch_size: 512
  prefetch_batches: 1
  use_gpu: true

logger:
  wandb:
    project: "EveNet"
    run_name: &logger_name "LEP-TauNu"
    tags: ["EveNet", "LEP"]
    entity: ytchou97-university-of-washington
    simplified: false
  local:
    save_dir: /tmp/tihsu/logs
    name: *logger_name
    version: "v1"

options:
  default: options.yaml

  Training:
    model_checkpoint_save_path: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/event-input/checkpoint
    model_checkpoint_load_path: null
    pretrain_model_load_path: null

  Dataset:
    normalization_file: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/event-input/normalization.pt

network:
  default: network.yaml

event_info:
  default: generated_event_info.yaml

resonance:
  default: resonance.yaml
