platform:
  data_parquet_dir: <data_parquet_dir>
  number_of_workers: 1
  resources_per_worker: {
    "CPU": 1,
    "GPU": 1,
  }
  batch_size: 4
  prefetch_batches: 1
  use_gpu: true

options:
  default: ../EveNet-Full/share/options/options.yaml

  prediction:
    output_dir: <output_dir>
    filename: <filename>
    save_point_cloud: true
    extra_save: []

  Training:
    total_epochs: 100
    epochs: 100
    diffusion_every_n_steps: 1
    model_checkpoint_save_path: null
    model_checkpoint_load_path: <ckpt_path>
    pretrain_model_load_path: null

    Components:
      Classification:
        include: true

      Regression:
        include: false

      Assignment:
        include: false

      Segmentation:
        include: false
        use_full_mask: true

      GlobalGeneration:
        include: false
        diffusion_steps: 2

      ReconGeneration:
        include: false
        diffusion_steps: 2

      TruthGeneration:
        include: true
        diffusion_steps: 2

    FAMO:
      turn_on: false
      detailed_loss: false

    EMA:
      enable: true
      replace_model_after_load: true

  Dataset:
    dataset_limit: 1.0
    normalization_file: <normalization_file>

network:
  default: ../EveNet-Full/share/network/network-20M.yaml

  Body:
    PET:
      feature_drop: 0.0

  TruthGeneration:
    feature_drop: 0.0

event_info:
  default: generated_event_info.yaml

resonance:
  default: resonance.yaml
